name: .NET Selenium CI (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build solution
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Step 5: Setup Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2

      # Step 6: Setup ChromeDriver
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          version: latest

      # Step 7: Run Tests (NUnit or ReqnRoll)
      - name: Run ReqnRoll Selenium Tests
        run: dotnet test --configuration Release --logger "console;verbosity=detailed" | tee TestResults.log

      # Step 8: Upload Test Results and Extent Reports
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Selenium_ExtentReports
          path: |
            **/ExtentReports/**
             TestResults.log

